name: Docker

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    tags:
      - v*

env:
  IMAGE_NAME: image

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sh bin/setup-github.sh

      - name: Build image
        run: docker-compose run --rm wordpress_phpunit phpunit

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v1
