name: PHP UNIT - Run tests

on: [push]
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn unit

      - name: CHECKING SYNTAX ERROR...
        run: yarn pretest:php

      - name: Run tests
        run: docker-compose run --rm wordpress_phpunit phpunit
